In [2]:
from itertools import product
from enum import Enum
from game import Game, Move

import numpy as np


In [3]:
c = tuple(product(range(5), repeat=2))

In [4]:
class MinOrMax(Enum):
    '''
    
    '''
    isMin = -1
    isMax = 1
    
a = MinOrMax.isMin

if a == MinOrMax.isMax:
    print("Yes")

In [5]:
players = [1, 2]
current_player_idx = 0

current_player_idx += 1
current_player_idx %= len(players)
print(current_player_idx)

current_player_idx += 1
current_player_idx %= len(players)
print(current_player_idx)

1
0


In [6]:
game = Game()

for row in range(game._board.shape[0]):
    for col in range(game._board.shape[1]):
        if np.random.randint(2) == 1:  # Genera casualmente 0 o 1
            game._board[row, col] = 1
        else:
            game._board[row, col] = 0

print(game._board)

numero_1_per_riga = np.sum(game._board == 1, axis=1)
numero_0_per_riga = np.sum(game._board == 0, axis=1)

numero_1_per_colonna = np.sum(game._board == 1, axis=0)
numero_0_per_colonna = np.sum(game._board == 0, axis=0)
    
# print (numero_1_per_riga)
# print (numero_0_per_riga)
# print (numero_1_per_colonna)
# print (numero_0_per_colonna)
# print()

numero_1_sulla_principale = np.sum(np.diag(game._board) == 1)
numero_1_sulla_secondaria = np.sum(np.diag(np.fliplr(game._board)) == 1)

numero_0_sulla_principale = np.sum(np.diag(game._board) == 0)
numero_0_sulla_secondaria = np.sum(np.diag(np.fliplr(game._board)) == 0)

print(numero_1_sulla_principale)
print(numero_1_sulla_secondaria)
print(numero_0_sulla_principale)
print(numero_0_sulla_secondaria)

POINTS = [0, 1, 5, 20, 50, 1000]
value = 0

for sequence in numero_1_per_riga:
    value += POINTS[sequence]
    
print(value)
    

[[1 0 1 0 0]
 [1 1 0 1 1]
 [0 1 0 0 0]
 [0 1 1 0 1]
 [0 1 1 0 1]]
3
2
2
3
96


In [7]:
a = float("inf") 
b = float("-inf")

c = MinOrMax.isMax

print(c.value)
abs(1-2)

1


1

In [14]:
game1 = Game()

for row in range(game1._board.shape[0]):
    for col in range(game1._board.shape[1]):
        if np.random.randint(2) == 1:  # Genera casualmente 0 o 1
            game1._board[row, col] = 1
        else:
            game1._board[row, col] = 0

game1.print()

[[1 0 1 0 1]
 [1 0 1 1 0]
 [1 0 1 0 0]
 [0 1 1 1 1]
 [0 0 1 1 1]]


In [22]:
print(game1._board[0, 1])
print(game1._board[1, 0])
print(game1._board[3, 4])

0
1
1
